version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: Zookeeper_container
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
  broker:
    image: wurstmeister/kafka
    container_name: Broker_container
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.137.1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper